version: '3.9'
services:
  dotnet_postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Homeworks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dotnet_network
  
  dotnet_rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: bool
      RABBITMQ_DEFAULT_PASS: bool
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - dotnet_network

  dotnet_minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    volumes:
    - dotnet_minio_data:/var/lib/minio/data
  
#  dotnet_mongodb:
#    image: mongo:latest
#    
#  dotnet_jaeger:
#    image: jaegertracing/all-in-one:latest
  
  dotnet_main:
    image: dotnet-web
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://*:80"
      RabbitMqConfig__Username: "bool"
      RabbitMqConfig__Password: "bool"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
      ConnectionStrings__Default: "Host=dotnet_postgres;Port=5432;Username=postgres;Password=postgres;Database=Homeworks;"
    ports:
      - "9000:80"
    depends_on:
      - dotnet_postgres
      - dotnet_rabbitmq
      - dotnet_storage
      
  dotnet_mailing:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    depends_on:
      - dotnet_rabbitmq
    environment:
      EmailConfig__Email: "jinx.httpserver@yandex.ru"
      EmailConfig__Host: "smtp.yandex.ru"
      EmailConfig__Port: "465"
      EmailConfig__Password: "kfgxrkizhidqhnyd"
      RabbitMqConfig__Username: "bool"
      RabbitMqConfig__Password: "bool"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
    networks:
      - dotnet_network

  dotnet_storage:
    image: dotnet-web
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Storage.API/Dockerfile
    ports:
      - 5098:8081
    depends_on:
      - dotnet_minio
    environment:
      MinioConfig__Username: admin
      MinioConfig__Password: admin
      MinioConfig__Endpoint: dotnet_minio
      MinioConfig__Port: 9000
      MinioConfig__WithSsl: false


volumes:
  postgres_data:

networks:
  dotnet_network:
    driver: bridge
